import type { SkillTemplate } from "./types";

export const builtinTemplates: SkillTemplate[] = [
  {
    templateId: "frontend-taste",
    name: "Frontend Taste",
    slug: "frontend-taste",
    description: "Helps AI coding agents create visually polished, production-ready frontend pages.",
    useCases: [
      "Improving landing pages, dashboards, and marketing pages generated by an AI coding tool.",
      "Turning plain UI requirements into refined visual direction, layout, spacing, and interaction guidance.",
      "Reviewing frontend work for visual hierarchy, responsiveness, accessibility, and polish."
    ],
    triggers: [
      "The user asks for a beautiful, polished, premium, modern, or production-ready frontend.",
      "The task involves landing pages, dashboards, app screens, visual redesign, or UI critique.",
      "The agent is about to generate CSS, React components, or layout-heavy frontend code."
    ],
    inputFormat: [
      "Product or page goal.",
      "Target audience and desired brand feel.",
      "Existing tech stack or design constraints.",
      "Reference examples, screenshots, or style preferences when available."
    ],
    outputFormat: [
      "Concise visual direction before implementation.",
      "Concrete layout, typography, color, spacing, asset, and interaction decisions.",
      "Implementation notes tied to the current framework.",
      "A final QA checklist covering desktop, mobile, accessibility, and visual fit."
    ],
    steps: [
      "Identify the product intent, audience, and most important user action.",
      "Choose a visual system with clear hierarchy, restrained colors, balanced spacing, and purposeful imagery.",
      "Implement the real usable screen first instead of a decorative placeholder.",
      "Check responsive behavior, text fit, contrast, empty states, hover states, and loading states.",
      "Iterate after visual inspection until the result looks coherent at mobile and desktop sizes."
    ],
    qualityStandards: [
      "The first viewport communicates the product clearly and shows a real interface or relevant visual asset.",
      "Spacing, type scale, colors, and component states feel intentional rather than default.",
      "The interface remains readable and usable on mobile and desktop.",
      "Buttons, forms, tabs, menus, and toolbars use familiar interaction patterns.",
      "The final result avoids generic template aesthetics and supports the user's actual domain."
    ],
    forbidden: [
      "Do not create a marketing-only landing page when the user asked for a usable app or tool.",
      "Do not rely on decorative gradients, floating blobs, or placeholder illustrations as the primary design.",
      "Do not let text overflow buttons, cards, panels, or mobile layouts.",
      "Do not introduce a new design system if the repository already has a clear one."
    ],
    safetyNotes: [
      "Do not collect, expose, or transmit credentials, tokens, private keys, or environment files.",
      "Do not run destructive shell commands while implementing visual changes.",
      "Prefer local assets or generated assets that the project can legally use."
    ],
    examplePrompt:
      "Create a frontend-taste skill for AI coding agents that helps them build polished SaaS landing pages with strong layout, typography, responsive behavior, and visual QA."
  },
  {
    templateId: "code-review",
    name: "Code Review",
    slug: "code-review",
    description: "Guides AI agents to review code changes for bugs, regressions, security risks, and missing tests.",
    useCases: [
      "Reviewing pull requests or local diffs before merge.",
      "Finding behavioral regressions, edge cases, security issues, and test gaps.",
      "Summarizing code changes with practical next steps."
    ],
    triggers: [
      "The user asks for review, PR review, code audit, or risk assessment.",
      "The agent receives a diff, pull request, branch comparison, or changed files.",
      "The user asks whether code is safe to merge."
    ],
    inputFormat: [
      "Repository context and target branch.",
      "Diff, changed files, or pull request number.",
      "Known product requirements or expected behavior.",
      "Test results when available."
    ],
    outputFormat: [
      "Findings first, ordered by severity.",
      "Each finding includes file, line, impact, and suggested fix.",
      "Open questions or assumptions.",
      "Brief summary and test coverage notes."
    ],
    steps: [
      "Read the surrounding code before judging the diff.",
      "Trace user-facing behavior, data flow, error paths, and permission boundaries.",
      "Check tests for meaningful coverage of changed behavior.",
      "Report only actionable issues that could matter in production.",
      "Keep summaries short and avoid blocking merge for style-only preferences."
    ],
    qualityStandards: [
      "Every finding is grounded in a concrete code location.",
      "Severity reflects real user, data, security, or maintainability impact.",
      "The review avoids speculation unless labeled as an assumption.",
      "No issue is duplicated across multiple comments.",
      "The final answer is concise and merge-oriented."
    ],
    forbidden: [
      "Do not rewrite the user's code unless explicitly asked.",
      "Do not report harmless style differences as defects.",
      "Do not ignore failing tests or missing coverage for risky changes.",
      "Do not reveal credentials, tokens, private keys, or secret values found in code."
    ],
    safetyNotes: [
      "Treat secrets as sensitive and recommend rotation if exposed.",
      "Do not execute untrusted scripts from the repository during review.",
      "Avoid destructive commands and avoid reading private environment files unless the user explicitly provides sanitized content."
    ],
    examplePrompt:
      "Create a code-review skill for AI coding agents that reviews pull requests for correctness, security, regressions, and missing tests, with findings first."
  },
  {
    templateId: "product-manager-interview",
    name: "Product Manager Interview",
    slug: "product-manager-interview",
    description: "Helps AI agents coach product manager candidates through strategy, execution, metrics, and behavioral interview practice.",
    useCases: [
      "Preparing for PM interviews at startups or large technology companies.",
      "Practicing product sense, analytics, execution, prioritization, and leadership questions.",
      "Turning rough experience notes into structured interview stories."
    ],
    triggers: [
      "The user asks for PM interview prep, mock interviews, product sense, metrics, or behavioral coaching.",
      "The user provides a target company, role level, product domain, or interview loop.",
      "The user wants feedback on an answer or story."
    ],
    inputFormat: [
      "Target role, company, and seniority.",
      "Interview type: product sense, execution, analytics, strategy, technical, or behavioral.",
      "Candidate background and constraints.",
      "Draft answer or practice prompt when available."
    ],
    outputFormat: [
      "Structured answer framework.",
      "A strong sample answer tailored to the role.",
      "Feedback on clarity, product judgment, metrics, tradeoffs, and executive presence.",
      "Follow-up drills and improvement checklist."
    ],
    steps: [
      "Clarify the interview type and success criteria.",
      "Select the right framework without forcing every answer into the same template.",
      "Build an answer with users, business goals, constraints, tradeoffs, metrics, and risks.",
      "Stress-test assumptions with realistic interviewer follow-ups.",
      "Give direct feedback and one focused revision path."
    ],
    qualityStandards: [
      "Answers are specific to the company, product surface, and role level.",
      "Metrics connect to user value and business outcomes.",
      "Tradeoffs are explicit and defensible.",
      "Behavioral answers show context, action, impact, and learning.",
      "Feedback is candid, kind, and immediately usable."
    ],
    forbidden: [
      "Do not fabricate personal work history for the candidate.",
      "Do not provide manipulative or dishonest interview tactics.",
      "Do not overfit every product question to a single rigid framework.",
      "Do not claim private knowledge of a company's current interview rubric."
    ],
    safetyNotes: [
      "Keep personal information minimal and avoid storing sensitive candidate details.",
      "Do not ask for private company documents or confidential interview questions.",
      "Encourage honest representation of experience and impact."
    ],
    examplePrompt:
      "Create a PM interview skill that helps candidates practice product sense, execution, metrics, and behavioral answers with structured feedback."
  },
  {
    templateId: "ai-evaluation",
    name: "AI Evaluation",
    slug: "ai-evaluation",
    description: "Guides AI agents to design robust evaluation tasks, rubrics, datasets, and analysis for large language model systems.",
    useCases: [
      "Designing evals for chatbots, coding agents, RAG systems, and workflow automations.",
      "Creating rubrics, golden datasets, failure taxonomies, and regression tests.",
      "Comparing model, prompt, tool, or retrieval changes."
    ],
    triggers: [
      "The user asks to evaluate an AI system, model, prompt, agent, or workflow.",
      "The task mentions benchmark, rubric, test set, hallucination, reliability, or regression.",
      "The user needs to decide whether an AI change is better or safer."
    ],
    inputFormat: [
      "System goal and target users.",
      "Failure modes and unacceptable behaviors.",
      "Candidate models, prompts, tools, or retrieval settings.",
      "Example tasks, real transcripts, or domain documents."
    ],
    outputFormat: [
      "Evaluation plan with success criteria.",
      "Task set design and sampling strategy.",
      "Rubric with score levels and examples.",
      "Analysis template for wins, regressions, risks, and launch recommendation."
    ],
    steps: [
      "Define the decision the evaluation must support.",
      "Map the user journey and high-risk failure modes.",
      "Create representative tasks, adversarial tasks, and regression cases.",
      "Choose automatic, human, or hybrid grading with a clear rubric.",
      "Summarize results with confidence level, limitations, and next experiments."
    ],
    qualityStandards: [
      "The eval measures user-relevant outcomes rather than vague model quality.",
      "Rubrics are specific enough for consistent graders.",
      "Datasets include normal, edge, and adversarial cases.",
      "Results separate quality, latency, cost, safety, and reliability.",
      "The final recommendation names residual risk."
    ],
    forbidden: [
      "Do not claim statistical confidence without enough samples.",
      "Do not use only cherry-picked examples.",
      "Do not optimize only for benchmark score while ignoring safety or user experience.",
      "Do not include private user data unless it has been properly sanitized."
    ],
    safetyNotes: [
      "Sanitize personally identifiable information and secrets before using transcripts.",
      "Include safety and abuse cases when the system can affect users or data.",
      "Do not upload confidential datasets to external services without explicit approval."
    ],
    examplePrompt:
      "Create an AI evaluation skill that designs rubrics, task sets, regression tests, and launch recommendations for LLM agent workflows."
  },
  {
    templateId: "github-trending-research",
    name: "GitHub Trending Research",
    slug: "github-trending-research",
    description: "Helps AI agents research trending GitHub projects and produce useful technical and market reports.",
    useCases: [
      "Tracking emerging open source repositories in AI, developer tools, infrastructure, and frontend.",
      "Comparing project positioning, adoption signals, architecture, and community activity.",
      "Producing concise reports for builders, investors, or engineering teams."
    ],
    triggers: [
      "The user asks for GitHub trending research, open source scouting, repo analysis, or star growth reports.",
      "The user provides GitHub repository links, topics, keywords, or time windows.",
      "The user wants a ranked list of promising projects."
    ],
    inputFormat: [
      "Research topic, language, ecosystem, or category.",
      "Time window and region if relevant.",
      "Repository URLs, keywords, or competitors.",
      "Preferred report format and depth."
    ],
    outputFormat: [
      "Ranked project list with links and short explanations.",
      "Signals: stars, recent activity, contributors, releases, docs, examples, and community traction.",
      "Technical summary: architecture, dependencies, use cases, strengths, and risks.",
      "Actionable takeaways and watchlist."
    ],
    steps: [
      "Clarify scope, time window, and audience.",
      "Collect repository metadata from primary sources whenever possible.",
      "Read README, releases, issues, examples, and docs for each shortlisted project.",
      "Compare projects using consistent criteria.",
      "Write a report that separates facts, interpretation, and recommendations."
    ],
    qualityStandards: [
      "Every project includes a source link and current observation date.",
      "Claims about popularity or activity are backed by visible signals.",
      "The report explains why each project matters now.",
      "Risks and caveats are included, not buried.",
      "The final ranking is useful for decision-making."
    ],
    forbidden: [
      "Do not invent repository statistics.",
      "Do not rely only on star count.",
      "Do not copy long README passages into the report.",
      "Do not expose credentials or private repository content."
    ],
    safetyNotes: [
      "Respect repository licenses and attribution.",
      "Do not access private repositories unless the user has authorized it.",
      "Avoid running unknown project install scripts during research."
    ],
    examplePrompt:
      "Create a GitHub trending research skill that analyzes popular open source AI agent projects and outputs a sourced technical report."
  },
  {
    templateId: "xiaohongshu-content-agent",
    name: "Xiaohongshu Content Agent",
    slug: "xiaohongshu-content-agent",
    description: "Helps AI agents plan, draft, and review Xiaohongshu content topics, posts, hooks, and retrospective analysis.",
    useCases: [
      "Generating content topics and post drafts for Xiaohongshu creators or brands.",
      "Improving hooks, titles, outlines, captions, and visual notes.",
      "Reviewing post performance and extracting repeatable content learnings."
    ],
    triggers: [
      "The user asks for Xiaohongshu, RED, 小红书, content topics, notes, hooks, captions, or content review.",
      "The user provides a niche, audience, product, personal brand, or performance data.",
      "The user wants a content calendar or post iteration plan."
    ],
    inputFormat: [
      "Account niche, audience, positioning, and content goal.",
      "Product, offer, experience, or topic source material.",
      "Tone preferences and examples of previous posts.",
      "Performance data when doing retrospective analysis."
    ],
    outputFormat: [
      "Topic angles with audience pain points and promise.",
      "Titles, hooks, outline, caption, visual direction, and call to action.",
      "Risk check for exaggerated claims, privacy, and platform fit.",
      "Post-mortem insights and next experiments when data is available."
    ],
    steps: [
      "Clarify audience, account positioning, and conversion goal.",
      "Generate multiple topic angles with distinct hooks and emotional drivers.",
      "Draft concise post structures with useful, believable details.",
      "Add visual notes, title options, hashtags, and interaction prompts.",
      "Review for authenticity, compliance, and learnings from prior performance."
    ],
    qualityStandards: [
      "Content feels specific, useful, and native to Xiaohongshu rather than generic marketing copy.",
      "Hooks are concrete and tied to real audience tension.",
      "Claims are believable and do not overpromise results.",
      "Visual direction supports the post instead of acting as decoration.",
      "Retrospectives identify repeatable patterns and next tests."
    ],
    forbidden: [
      "Do not fabricate personal experiences, medical results, income claims, or user testimonials.",
      "Do not generate deceptive engagement bait.",
      "Do not include private user data, private messages, or unapproved screenshots.",
      "Do not promise guaranteed platform growth."
    ],
    safetyNotes: [
      "Avoid sensitive personal data and private account information.",
      "Flag regulated categories such as medical, finance, and legal claims for extra review.",
      "Respect platform rules, copyright, and brand disclosure requirements."
    ],
    examplePrompt:
      "Create a Xiaohongshu content agent skill that helps plan topics, draft native posts, improve hooks, and review performance learnings."
  }
];

export function listTemplates(): SkillTemplate[] {
  return builtinTemplates.map((template) => ({ ...template }));
}

export function getTemplateById(templateId: string): SkillTemplate | undefined {
  return builtinTemplates.find((template) => template.templateId === templateId || template.slug === templateId);
}
