import type { SkillDefinition } from "../types";
import { renderStandardSections } from "./shared";

export function renderAgentsMd(skill: SkillDefinition): string {
  return `# Agent Skill: ${skill.name}

This repository contains an AI agent skill package generated by Agent Skill Studio.

${renderStandardSections(skill)}
## Tool Notes

- Claude Code can use the Claude skill file under \`.claude/skills/${skill.slug}/SKILL.md\`.
- Codex can use the Codex skill file under \`.codex/skills/${skill.slug}/SKILL.md\`.
- Cursor can use the Cursor rule under \`.cursor/rules/${skill.slug}.mdc\`.
- Gemini CLI can use the context file under \`.gemini/${skill.slug}.md\`.
`;
}
